### PR TITLE
fix(webpack): better merge for configs and fallback for async plugins

### LINKED ISSUE #855: Webpack error with imported variables
## Environment

- Linaria version: `3.0.0-beta.13`
- Bundler (+ version): `webpack@5.59.0`
- Node.js version: `14.15.1`
- OS: `macOS@11.6`

## Description

We've been using Linaria successfully in our projects for a while now. However, I have encountered a strange issue recently with using the Webpack loader, but which works with CLI.

If I use a constant that is imported from another module, Webpack blows up with `finishWithoutResolve` error.

For example:
```js
import { styled } from '@linaria/react';
import { device, size } from './breakpoints';

const Description = styled.p`
  background-color: orange;
 
  @media ${ device.tablet } {    
    background-color: blue;
  }
`;
```

Fails to build, erroring with:
`Can't resolve './breakpoints' in '/path/to/linaria-webpack-bug/src'`

## Reproducible Demo

A reproducible repo with steps is available here:
https://github.com/kinetifex/linaria-webpack-bug

### PR DESCRIPTION
**Pull request by Anber**
## Motivation

Fixes #855 and regression from #830

## Summary

In #830 we decided to use the whole Webpack configuration in Linaria's resolver. It appeared, that it wasn't the wisest decision because it introduced a lot of breaking changes. This PR introduces a better merge for Webpack config with default Linaria's config and adds a fallback if Webpack configuration breaks the resolver by using some async plugins.

### CODE REVIEW

File: packages/webpack5-loader/src/index.ts [hunk 1]
```diff
@@ -56,18 +61,47 @@ export default function webpack5Loader(
...
-    // There is this.resolve, but it's asynchronous
-    // Another option is to read the webpack.config.js, but it won't work for programmatic usage
-    // This API is used by many loaders/plugins, so hope we're safe for a while
-    {
-      ...(this._compilation?.options.resolve ?? {}),
+  // this._compilation is a deprecated API
+  // However there seems to be no other way to access webpack's resolver
+  // There is this.resolve, but it's asynchronous
+  // Another option is to read the webpack.config.js, but it won't work for programmatic usage
+  // This API is used by many loaders/plugins, so hope we're safe for a while
```
Comment (ntucker) [inline packages/webpack5-loader/src/index.ts:68]: this._compilation is undefined in the latest webpack

Comment (ntucker) [reply packages/webpack5-loader/src/index.ts:68]: Does https://webpack.js.org/api/loaders/#thisgetresolve work?
